key: holesky
name: Holesky Testnet
description: "This is the Holešky (Holešovice) test network, the previous generation of long-lived testnets for Ethereum. It uses free fake ETH to make fake validators.\n\nHolesky will be deprecated soon; Hoodi will replace it as the primary testnet as more protocols and tools are deployed to it."
networkResources:
  ethNetworkName: holesky
  chainID: 17000
  genesisForkVersion: 0x01017000
  multicallAddress: 0x0540b786f03c9491f3a2ab4b0e3ae4ecd4f63ce7
  balanceBatcherAddress: 0xfAa2e7C84eD801dd9D27Ac1ed957274530796140
  txWatchUrl: https://holesky.etherscan.io/tx
  flashbotsProtectUrl: https://rpc-holesky.flashbots.net/
  mevBlockerUrl: ""
  depositContractAddress: 0x4242424242424242424242424242424242424242
  depositContractBlock: 0
  capellaForkVersion: 0x04017000
  capellaForkEpoch: 256
defaultConfigSettings:
hyperdriveResources:
  nodeSetApiUrl: https://nodeset.io/api
  encryptionPubkey: age1hs87f8pl369tel4xpprtmaxwhg2e3gynvz8q45h48hed4m4h4d0s6t8caa